import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
const read=p=>fs.readFileSync(p,'utf8'),source=read('utils/backdropMasks.ts');
test('neon hue B and dispersion shift change only their shared defaults',()=>{const effects=read('utils/glEffects.ts');assert.match(effects,/id: 'fxY2kHueB'[^\n]+def: 260/);assert.match(effects,/id: 'fxRgbAmount'[^\n]+def: 5/);});
test('five current materials hide thermal and old circles without deleting draft support',()=>{for(const id of ['mask-mosaic','mask-bricks','mask-frost','mask-negative','mask-monochrome'])assert.ok(source.includes(`id:'${id}'`));for(const id of ['mask-thermal','mask-frost-circle','mask-frost-feather'])assert.ok(!source.includes(`id:'${id}'`));assert.ok(source.includes("kind==='mask-thermal'"));for(const file of ['components/CollageTool.tsx','components/GridLayoutTool.tsx'])assert.ok(read(file).includes("['遮罩', MASK_SHAPE_ITEMS]"));});
test('masks use corresponding effect shaders, not approximate unrelated filters',()=>{assert.ok(source.includes("body('fxMosaic')"));assert.ok(source.includes("body('fxGlass')"));assert.match(source,/c=1\.-c/);assert.match(source,/weights\[25\]/);});
test('feather control belongs only to feathered circle and commits once per frame',()=>{const controls=read('components/BackdropMaskControls.tsx');assert.match(controls,/kind==='mask-frost-feather'.*label:'羽化'/);assert.ok(controls.includes('requestAnimationFrame'));assert.ok(controls.includes('onPointerCancel={flush}'));});
test('geometry maps mask selection to its exact square or circle',()=>{const grid=read('components/GridLayoutTool.tsx'),start=grid.indexOf('export const shapePathD ='),part=grid.slice(start,grid.indexOf('\n};',start)+3);const scope={exports:{},r3:n=>Math.round(n*1000)/1000};vm.runInNewContext(ts.transpileModule(part,{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,scope);const path=scope.exports.shapePathD;for(const kind of ['mask-mosaic','mask-bricks','mask-negative','mask-frost'])assert.equal(path(kind,160,100),path('square',160,100));for(const kind of ['mask-frost-circle','mask-frost-feather'])assert.equal(path(kind,160,100),path('circle',160,100));});
test('preview replays lower ink only and export samples already-composited ink',()=>{const scene=read('components/ClassicVectorScene.ts');assert.match(scene,/entry\.z<z/);assert.match(scene,/this\.activePhoto=null;this\.capturingBackdrop=true/);assert.match(scene,/this\.activePhoto=active/);const grid=read('components/GridLayoutTool.tsx');assert.match(grid,/scene\.backdrop\(ctx/);assert.match(grid,/drawBackdropMask\(ctx,fImg\.shape!,fImg\.width,fImg\.height,fImg\)/);});
test('moving masks cannot reuse a stale partial pattern paint or blank wave layer',()=>{const creative=read('components/CollageTool.tsx');assert.match(creative,/GRID_SHAPE_KINDS\.has\(o\.kind\)\|\|isBackdropMask\(o\.kind\)/);assert.match(creative,/!objects\.some\(o => isVideoEl\(o\.img\)\|\|isBackdropMask\(o\.kind\)\)/);});
test('allocation is clipped to viewport and GPU loss has a full-resolution fallback',()=>{assert.match(source,/Math\.min\(width,/);assert.match(source,/Math\.min\(height,/);assert.match(source,/if\(renderer===undefined\|\|renderer\?\.gl\.isContextLost\(\)\)/);assert.match(source,/fallbackMask\(source,m,w,h,kind,settings,b,sigma\)/);assert.match(source,/original=data\.data\.slice\(\)/);});
test('art frosted glass uses the requested name',()=>{assert.ok(read('utils/artMaterials.js').includes("['glass','毛玻璃']"));});
test('unused sampler is initialized before the first material frame',()=>{assert.match(source,/for\(const t of \[this.input,this.first,this.second,this.cells\]\)/);assert.match(source,/texSubImage2D/);assert.ok(!source.includes('this.width>width*2'));});
test('mask controls expose shape, requested controls and shape-only negatives',()=>{const c=read('components/BackdropMaskControls.tsx');assert.match(c,/shapeOnly=kind==='mask-negative'\|\|kind==='mask-negative-mono'/);assert.match(c,/!shapeOnly&&kind!=='mask-mosaic'/);for(const name of ['方形','圓形','星形'])assert.ok(c.includes(name));assert.match(c,/kind==='mask-mosaic'.*label:'格數'.*\?\?15/);assert.ok(!c.includes("label:'透明度'"));assert.match(c,/kind!=='mask-mosaic'&&kind!=='mask-bricks'/);});
test('nonlinear mask scenes never use photo endpoint interpolation',()=>{const c=read('components/CollageTool.tsx');assert.match(c,/const hasBackdrop=objectsRef.current.some/);assert.match(c,/!previewCapture&&!hasBackdrop/);assert.match(c,/if\(!hasBackdrop&&targetCanvas/);});
test('backdrop materials never enter transparent static-object tile caches',()=>{const c=read('components/CollageTool.tsx');assert.match(c,/const eligible = isMain && !f && o.type !== 'image' && !isBackdropMask\(o.kind\)/);});
test('removed classic scene surfaces release mask GPU contexts',()=>{const c=read('components/ClassicVectorScene.ts');assert.match(c,/disposeBackdropMasks\(canvas\);canvas.remove\(\)/);});
test('mask source reuse tracks lower ink and opts animations and unknown DOM layers out',()=>{const c=read('components/CollageTool.tsx'),scene=read('components/ClassicVectorScene.ts');assert.match(c,/sourceStamp=isMain&&!animRef.current&&!f/);assert.match(c,/o.below\?item.below&&index<maskIndex:item.below\|\|index<maskIndex/);assert.match(scene,/revision===undefined\)cacheable=false/);assert.match(scene,/backdropCacheStamp=cacheable\?JSON.stringify\(keys\):undefined/);});
test('warm thumbnail banks reuse their exact canvases instead of recopying or keeping full-source DOM images',()=>{const c=read('components/GridLayoutTool.tsx');assert.match(c,/host.replaceChildren\(shown\)/);assert.match(c,/paintedKey!==cacheKey&&<img/);assert.match(c,/thumb.parentElement\?\.isConnected/);});
test('tab switching does not key photo endpoints on chrome selection or synchronously read GPU pixels',()=>{const c=read('components/CollageTool.tsx');const part=c.slice(c.indexOf('const gpuSceneFingerprint='),c.indexOf('regionGpuSceneKey.current=gpuSceneFingerprint'));for(const ui of ['baseSelected','selectedTarget','objDragging','shapeSel'])assert.ok(!part.includes(ui));assert.ok(c.includes('compactSceneValue'));});
test('six alternating native-viewport masks retain distinct source textures without upload thrashing',()=>{
 let serial=0;const diagnostics={uploads:0,reuses:0},constant=new Map();
 const gl=new Proxy({createTexture:()=>({id:++serial}),createProgram:()=>({}),createShader:()=>({}),createFramebuffer:()=>({}),getParameter:()=>16384,getShaderParameter:()=>true,getProgramParameter:()=>true,getUniformLocation:()=>({}),getAttribLocation:()=>0,isContextLost:()=>false},{get:(o,k)=>k in o?o[k]:typeof k==='string'&&k===k.toUpperCase()?(constant.has(k)?constant.get(k):(constant.set(k,constant.size+1),constant.get(k))):()=>{}});
 class Matrix{constructor(v=[1,0,0,1,0,0]){[this.a,this.b,this.c,this.d,this.e,this.f]=v;}inverse(){return new Matrix();}}
 const scope={exports:{},header:'',vertex:'',material:'',batchMaterial:'',cellMaterial:'',batchCellMaterial:'',blur:'',HTMLImageElement:class{},maskGeometry:()=> 'square',maskPhysicalBounds:(_m,_w,_h,w,h)=>({left:0,top:0,width:w,height:h}),document:{createElement:()=>({width:1,height:1,getContext:()=>gl})},DOMMatrix:Matrix,performance:{now:()=>0},backdropMaskDiagnostics:diagnostics};
 const cls=source.slice(source.indexOf('class MaskGpu'),source.indexOf('const renderers='))+'\nexport {MaskGpu};';
 vm.runInNewContext(ts.transpileModule(cls,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,scope);
 const renderer=new scope.exports.MaskGpu(),canvas={width:1338,height:1785},m=new Matrix(),bounds={left:0,top:0,width:1338,height:1785};
 for(let frame=0;frame<30;frame++)for(let i=0;i<6;i++)renderer.render(canvas,m,350,400,'mask-negative',{maskAmount:100},bounds,0,`lower-${i}`,`mask-${i}`);
 assert.equal(diagnostics.uploads,6);assert.equal(diagnostics.reuses,174);assert.equal(renderer.sources.size,6);
 renderer.render(canvas,m,350,400,'mask-negative',{maskAmount:100},bounds,0,'changed','mask-3');assert.equal(diagnostics.uploads,7);
 for(let i=6;i<20;i++)renderer.render(canvas,m,350,400,'mask-negative',{maskAmount:100},bounds,0,`lower-${i}`,`mask-${i}`);
 assert.ok(renderer.sources.size<=8);assert.ok([...renderer.sources.values()].reduce((n,s)=>n+s.width*s.height,0)<=32*1024*1024);
 const before=diagnostics.uploads,photo={source:canvas,key:'photo-native',rect:[0,0,1338,1785],uv:[0,0,1,1],clip:[0,0,1338,1785]},layer={kind:'mask-negative',w:350,h:400,matrix:m,settings:{maskAmount:100},opacity:1};
 for(let i=0;i<30;i++){photo.rect=[i,i,1338+i,1785+i];renderer.renderBatch(canvas,[layer],[photo]);}
 assert.equal(diagnostics.uploads-before,1,'preview geometry only changes uniforms, never the photo upload');
});
test('native mask photo route does not flatten vector/pattern scenes or incomplete photo cells',()=>{const c=read('components/CollageTool.tsx');assert.match(c,/hasBackdrop&&maskPhotosReady/);assert.match(c,/!holes.length&&!animRef.current&&!swapSource/);assert.match(c,/objects.every\(o=>!o.below&&o.type==='shape'&&isBackdropMask/);assert.match(c,/regionRects\(photoRegion,iw,ih\).length===photoRegion.photos.length/);assert.match(source,/sourcePixels>64\*1024\*1024/);});
