// Development-only, mounted React controls and pointer lifecycle regression.
void (async()=>{
  const wait=async(n=4)=>{for(let i=0;i<n;i++)await new Promise<void>(r=>requestAnimationFrame(()=>r()));};
  while(!document.querySelector('canvas[data-paint-count]'))await wait();
  await wait(25);
  const report:any={kind:'creative-mask-interaction',ua:navigator.userAgent,checks:[]};
  const check=(name:string,pass:boolean,details?:any)=>report.checks.push({name,pass,details});
  const click=(name:string)=>(document.querySelector(`button[aria-label="${name}"]`) as HTMLButtonElement)?.click();
  (document.querySelectorAll('footer button')[1] as HTMLButtonElement).click();await wait();
  const sizes=Array.from(document.querySelectorAll('[data-pattern-choice]')).map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height}));
  check('all 20 pattern buttons share first-row width and height',sizes.length===20&&sizes.every(s=>Math.abs(s.w-sizes[0].w)<.02&&s.h===sizes[0].h),sizes);
  click('參數');await wait();
  const count=document.querySelector('input[type=range][max="30"]') as HTMLInputElement;
  Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(count,'0');count.dispatchEvent(new Event('input',{bubbles:true}));count.dispatchEvent(new Event('change',{bubbles:true}));await wait();
  const mask=document.createElement('canvas');mask.width=600;mask.height=800;const g=mask.getContext('2d')!;
  const grad=g.createLinearGradient(0,0,600,800);grad.addColorStop(0,'#fb3050');grad.addColorStop(.5,'#80ff40');grad.addColorStop(1,'#3150ff');g.fillStyle=grad;g.fillRect(0,0,600,800);g.fillStyle='white';g.fillRect(270,100,30,600);
  const blob=await new Promise<Blob>(r=>mask.toBlob(b=>r(b!)));
  const dt=new DataTransfer();dt.items.add(new File([blob],'mask.png',{type:'image/png'}));
  const input=document.querySelector('input[aria-label="上傳遮罩圖片"]') as HTMLInputElement;input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));
  while(!document.querySelector('canvas[data-mask-photo-transform]'))await wait();await wait(15);
  const canvas=document.querySelector('canvas[data-mask-photo-transform]') as HTMLCanvasElement;
  const stage=canvas.closest('main')!.querySelector('[class*="absolute inset-0 overflow-hidden"]')!;
  const rect=canvas.getBoundingClientRect(), y=rect.top+rect.height*.07;
  const event=(type:string,id:number,x:number,py=y)=>stage.dispatchEvent(new PointerEvent(type,{pointerId:id,pointerType:'touch',isPrimary:id===1,clientX:x,clientY:py,bubbles:true,buttons:type==='pointerup'?0:1}));
  const read=()=>JSON.parse(canvas.dataset.maskPhotoTransform!);
  const hash=()=>{const d=canvas.getContext('2d')!.getImageData(0,0,canvas.width,canvas.height).data;let h=0;for(let i=0;i<d.length;i+=101)h=(Math.imul(h,31)+d[i])|0;return h;};
  const x1=rect.left+rect.width*.8,x2=rect.left+rect.width*.9;
  event('pointerdown',1,x1);event('pointerup',1,x1);await wait();
  check('tap selects custom mask photo',!!document.querySelector('[data-mask-photo-selection]'));
  const initial=read(),before=hash();event('pointerdown',1,x1);event('pointerdown',2,x2);await wait();
  check('second finger alone does not resize or shift mask',JSON.stringify(read())===JSON.stringify(initial));
  event('pointermove',1,rect.left+rect.width*.72);event('pointermove',2,rect.left+rect.width*.98);await wait();
  event('pointerup',1,x1);event('pointerup',2,x2);await wait();
  const zoomed=read();check('pinch changes mask size and visible pixels',zoomed.w>initial.w*2&&hash()!==before,{initial,zoomed});
  const startHash=hash();event('pointerdown',1,x1);event('pointermove',1,x1+rect.width*.08,y+rect.height*.08);await wait();
  const dragged=read();event('pointerdown',2,x2);await wait();
  check('drag to pinch preserves latest crop',JSON.stringify(dragged)===JSON.stringify(read()),{dragged,next:read()});
  event('pointerup',1,x1);event('pointerup',2,x2);await wait();
  check('drag changes crop without revealing empty edges',hash()!==startHash&&dragged.x<=0&&dragged.y<=0&&dragged.x+dragged.w>=dragged.frameW&&dragged.y+dragged.h>=dragged.frameH,dragged);
  report.pass=report.checks.every((c:any)=>c.pass);
  const out=document.createElement('pre');out.id='mask-audit-result';out.textContent=JSON.stringify(report,null,2);out.style.cssText='position:fixed;top:58px;left:8px;max-height:180px;overflow:auto;z-index:999999;background:#111e;color:#fff;font-size:10px;max-width:90vw';document.body.append(out);
  await fetch('http://127.0.0.1:5192/results',{method:'POST',body:JSON.stringify(report)}).catch(()=>{});
})();
