import {ASCII_PRESETS,ASCII_RANGE_LOWS} from './asciiControls.js';
export interface AsciiOptions { characters:string; columns:number; low:number; high:number; metric:number; invert:boolean; color:boolean; background:boolean; glow?:number; ranges?:number[]; }
export const ASCII_DEFAULTS:AsciiOptions={characters:ASCII_PRESETS[0],columns:96,low:20,high:100,metric:0,invert:false,color:false,background:true,glow:0,ranges:[...ASCII_RANGE_LOWS]};
/** Persistent GPU image + glyph atlas. Slider changes only update uniforms. */
export class AsciiRenderer {
 private gl:WebGLRenderingContext; private program:WebGLProgram; private textures:WebGLTexture[]=[]; private buffer:WebGLBuffer; private chars=''; private count=1;
 constructor(private canvas:HTMLCanvasElement){
  const gl=canvas.getContext('webgl',{alpha:false,antialias:false,preserveDrawingBuffer:true});if(!gl)throw Error('此裝置暫時無法啟用藝術預覽，請重新開啟。');this.gl=gl;
  const compile=(type:number,code:string)=>{const s=gl.createShader(type)!;gl.shaderSource(s,code);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)||'Shader failed');return s;};
  const vs=compile(gl.VERTEX_SHADER,'attribute vec2 p;varying vec2 uv;void main(){uv=p*.5+.5;gl_Position=vec4(p,0.,1.);}');
  const fs=compile(gl.FRAGMENT_SHADER,`precision highp float;varying vec2 uv;uniform sampler2D photo,atlas,haloAtlas;uniform vec2 size;uniform float columns,low,high,metric,invert,colored,count,original,background,glow;
  float lum(vec3 c){return dot(c,vec3(.2126,.7152,.0722));}
  void main(){vec3 raw=texture2D(photo,uv).rgb;if(original>.5){gl_FragColor=vec4(raw,1.);return;}vec2 grid=vec2(columns,columns*size.y/size.x*.6);vec2 cell=floor(uv*grid),center=(cell+.5)/grid;vec3 c=texture2D(photo,center).rgb;float v=lum(c);if(metric>.5&&metric<1.5){vec2 t=1./size;float x=lum(texture2D(photo,center+vec2(t.x*2.,0.)).rgb)-lum(texture2D(photo,center-vec2(t.x*2.,0.)).rgb);float y=lum(texture2D(photo,center+vec2(0.,t.y*2.)).rgb)-lum(texture2D(photo,center-vec2(0.,t.y*2.)).rgb);v=clamp(length(vec2(x,y))*4.,0.,1.);}else if(metric>2.5){v=1.-v;}else if(metric>1.5){v=max(c.r,max(c.g,c.b))-min(c.r,min(c.g,c.b));}v=clamp((v-low)/max(.001,high-low),0.,1.);v=mix(v,1.-v,invert);float gate=step(.001,v);float id=min(count-1.,floor(v*count));vec2 q=fract(uv*grid);vec2 at=vec2((id+q.x)/count,q.y);float ink=texture2D(atlas,at).a*gate;float halo=texture2D(haloAtlas,at).a*gate*glow;vec3 fg=mix(vec3(1.),c,colored);gl_FragColor=vec4(mix(min(vec3(1.),mix(vec3(.025),raw,background)+fg*halo*.85),fg,ink),1.);}`);
  const program=gl.createProgram()!;gl.attachShader(program,vs);gl.attachShader(program,fs);gl.bindAttribLocation(program,0,'p');gl.linkProgram(program);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('藝術預覽初始化失敗');this.program=program;
  this.buffer=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,this.buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);
  for(let i=0;i<3;i++){const t=gl.createTexture()!;this.textures.push(t);gl.activeTexture(gl.TEXTURE0+i);gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);}
 }
 setImage(image:HTMLImageElement){const g=this.gl;const max=g.getParameter(g.MAX_TEXTURE_SIZE);if(image.naturalWidth>max||image.naturalHeight>max)throw Error('照片超過此裝置的 GPU 尺寸上限，請使用較小的照片。');this.canvas.width=image.naturalWidth;this.canvas.height=image.naturalHeight;g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,this.textures[0]);g.pixelStorei(g.UNPACK_FLIP_Y_WEBGL,1);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,g.RGBA,g.UNSIGNED_BYTE,image);}
 draw(o:AsciiOptions,original=false){const g=this.gl;const chars=[...o.characters].slice(0,48);if(!chars.length)chars.push('@');const key=chars.join('');if(key!==this.chars){this.chars=key;this.count=chars.length;const a=document.createElement('canvas');a.width=64*chars.length;a.height=96;const c=a.getContext('2d')!;c.fillStyle='white';c.textAlign='center';c.textBaseline='middle';c.font='64px monospace';chars.forEach((ch,i)=>c.fillText(ch,i*64+32,48,60));g.activeTexture(g.TEXTURE1);g.bindTexture(g.TEXTURE_2D,this.textures[1]);g.pixelStorei(g.UNPACK_FLIP_Y_WEBGL,1);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,g.RGBA,g.UNSIGNED_BYTE,a);const halo=document.createElement('canvas');halo.width=a.width;halo.height=a.height;const hc=halo.getContext('2d')!;for(const [i,weight] of [.55,.3,.15].entries()){hc.globalAlpha=weight;hc.filter='blur('+(96*.045*(i+1)*.5)+'px)';hc.drawImage(a,0,0);}g.activeTexture(g.TEXTURE2);g.bindTexture(g.TEXTURE_2D,this.textures[2]);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,g.RGBA,g.UNSIGNED_BYTE,halo);}
  g.useProgram(this.program);g.bindBuffer(g.ARRAY_BUFFER,this.buffer);g.enableVertexAttribArray(0);g.vertexAttribPointer(0,2,g.FLOAT,false,0,0);g.viewport(0,0,this.canvas.width,this.canvas.height);const u=(n:string)=>g.getUniformLocation(this.program,n);g.uniform1i(u('photo'),0);g.uniform1i(u('atlas'),1);g.uniform1i(u('haloAtlas'),2);g.uniform2f(u('size'),this.canvas.width,this.canvas.height);for(const [k,v] of Object.entries({columns:o.columns,low:o.low/100,high:o.high/100,metric:o.metric,invert:+o.invert,colored:+o.color,count:this.count,original:+original,background:+o.background,glow:(o.glow||0)/100}))g.uniform1f(u(k),v);g.drawArrays(g.TRIANGLES,0,6);
 }
 dispose(){const g=this.gl;this.textures.forEach(t=>g.deleteTexture(t));g.deleteBuffer(this.buffer);g.deleteProgram(this.program);}
}
